---
title: "Steps to Self Realization"
date: 2021-04-25T07:17:29+05:30
draft: false
toc: true
categories: ["Vedānta"]
tags: ["Spirituality", "Yoga", "ŚrimadBhagvadGītā"]
---

ādiŚankara in aparokṣānūbhūti describes 15 steps to direct realization of ātman (Self, Consciousness, Brahman).
This article lists them briefly along with guidance available from other revered texts.
For detailed study, please see References at the end.


** 1. yamḥ - The purification of the Senses

The restraint of all the senses by means of such knowledge as "All this is Brahman" is called yamḥ

From Yogasūtra, it consists of:
- ahiṃsā: non-killing and non-hurting
- satya: Truthfulness
- astey: non-stealing
- brahmacarya: continence
- aparigṛuh: non-receiving and non-hoarding beyond needs


** 2. niyamḥ - The purification of the mind

The continuous flow of only one kind of thought(This ātman is Brahman), to the exclusion of all other thoughts in called niyamḥ

From Yogasūtra, it consists of:
- shaucḥ: maintaining hygiene and purification by staying away from attachment, aversion and anger
- saṃtoṣḥ: contentment
- tapḥ: bearing all physical/mental obstacles and not swaying away from practice
- svādhyāyḥ: studying self and related scriptures
- īśvar-praṇidhānāni: surrendering to God


** 3. tyāgḥ - Renunciation
The real renunciation is knowing that All this is covered by Brahman, hence, coveting nothing yet performing duties righteously.

#+begin_quote
ॐ ईशा वास्यमिदँ सर्वं यत्किञ्च जगत्यां जगत् ।

तेन त्यक्तेन भुञ्जीथा मा गृधः कस्यस्विद्धनम् ।।

Om. All this - whatsoever moves on the earth - should be covered by the Lord. Protect yourself through that detachment.
Do not covet, for whose is wealth!

īśopniśad
#+end_quote


** 4. maunṃ - Silence
The wise should always be one with the Silence where words and mind fail to reach. Since Brahman is inexpressible,
Brahmavādin (teachers of brahman) instructs seekers to practice silence.


** 5. deśḥ - Place
#+begin_quote
योगी युञ्जीत सततमात्मानं रहसि स्थितः।

एकाकी यतचित्तात्मा निराशीरपरिग्रहः।।6.10।।


The Yogin should constantly fix his mind on Yoga, remaining in a solitary place all alone,
controlling his thought and mind, free from desire and sense of possession.

[[https://www.gitasupersite.iitk.ac.in/srimad?language=dv&field_chapter_value=6&field_nsutra_value=10&etadi=1&choose=1][ŚrimadBhagvadGītā]]
#+end_quote

Brahman alone is the Solitude, for there is nothing second to it. Abide in that Solitude always.


** 6. kāltā - Time

#+begin_quote
लयविक्षेपयोः सन्धौ मनस्तत्र निरामिषम् ।

स सन्धिः साधितो येन स मुक्तो नात्र संशयः ॥9॥

The mind is desire-less at the conjunction of the dissolution and projection. The one who has
achieved that conjunction is said to be liberated. In this matter, there is no doubt whatsoever.

Sadacharanusandhanami
#+end_quote

So, the time of conjunctions i.e. morning and evening are suitable for practice. As practice gets
advanced, one meditates on the conjunctions of breaths - a nameless chant which each body chants
all the time.

Brahman alone is the Time, for That makes this world appear instantly like a dream.


** 7. āsanṃ - Posture
One should assume posture (āsana) in which meditation on Brahman flows spontaneously,
and not the postures which cause any discomfort and distract the mind.

These three āsanas are prescribed: sukhāsana, sidhāsana and padmāsana

How should be the seat?

#+begin_quote
शुचौ देशे प्रतिष्ठाप्य स्थिरमासनमात्मनः।

नात्युच्छ्रितं नातिनीचं चैलाजिनकुशोत्तरम्।।6.11।।

Having established for himself, in a clean spot, a firm seat, which is neither too hight nor too low,
and covering it with cloth, deer-skin and Kusa grass in the reverse order.

ŚrimadBhagvadGītā
#+end_quote


** 8. mūlbandhḥ - The Restraining Root

That (Brahman) is the root of all existence and on which the restraint of the mind is based.
In Rāja Yoga, mūlbandhḥ is a posture, but in Vedāntic light, the emphasis is on restraining the mind
than on posture itself.

#+begin_quote
तत्रैकाग्रं मनः कृत्वा यतचित्तेन्द्रियक्रियः।

उपविश्यासने युञ्ज्याद्योगमात्मविशुद्धये।।6.12।।

There, sitting on the seat, with the mind concentrated and holding the mind and senses in check,
he should practise Yoga for the purification of the self.

ŚrimadBhagvadGītā
#+end_quote


** 9. dehsāmyaṃ - The Equipoise of the body
#+begin_quote
समं कायशिरोग्रीवं धारयन्नचलं स्थिरः। 6.13(1)

Holding the trunk, head and neck erect, motionless and steady

ŚrimadBhagvadGītā
#+end_quote

Śankara says that absorption in the uniform Brahman should be known as the equipoise of the limbs.
Otherwise, mere straightening of the body like that of a dried up tree is no equipoise.


** 10. dṛksthitiḥ - The firm and the noblest vision

#+begin_quote
संप्रेक्ष्य नासिकाग्रं स्वं दिशश्चानवलोकयन्।।6.13।।

Gazing at the tip of the nose, and looking not in any direction.

ŚrimadBhagvadGītā
#+end_quote

Gazing at the tip of the nose is a simile to convert ordinary vision into one of knowledge where one
views the world as Brahman Itself. This is the noblest vision. Or, one should direct one's vision to
That alone where all distinction of the seer, sight and the seen ceases.


** 11. prānayāmḥ - The control of the vital forces
Since entire dependence of breath is on the mind and reverse is partially true, Śankara instructs to
restrain all mental (cittā) modifications as Brahman alone, and describes below as real course of
prānayāmḥ:

| Breathing Flow | Yogic Name | Thought                          |
|----------------+------------+----------------------------------|
| out            | recaka     | Negation of the phenomenal world |
| in             | pūraka     | I am verily Brahman              |
| hold           | kumbhaka   | steadiness of above thought      |

#+begin_quote
प्रशान्तात्मा विगतभीर्ब्रह्मचारिव्रते स्थितः।

मनः संयम्य मच्चित्तो युक्त आसीत मत्परः।।6.14।।

Serene and fearless, firm in the vow of celibacy, holding the mind in check and fixing the thought on Me(ātman),
one should sit in Yoga, intent on Me (ātman).

ŚrimadBhagvadGītā
#+end_quote


** 12. pratyāhārḥ - The withdrawal of the mind
Whatever the senses perceive, it calls for a related form in mind stuff. So, pratyāhārḥ is drawing in of
the organs by giving up their own objects and taking the form of mind as it were without modifications.

Śankara instructs that it is only possible by absorption of the mind in the Supreme Consciousness by realizing
ātman in all objects.

#+begin_quote
युञ्जन्नेवं सदाऽऽत्मानं योगी नियतमानसः।

शान्तिं निर्वाणपरमां मत्संस्थामधिगच्छति।।6.15।।

Ever applying his mind in this way, the Yogin of controlled mind, attains the peace
which is the summit of beatitude and which abides in Me (ātman)

ŚrimadBhagvadGītā
#+end_quote


** 13. dhāraṇā - The Supreme Concentration
Now, the mind is purified to concentrate on any object at will. ŚriŚankara instructs that Supreme Concentration is that
when the mind comes into contact of any object, becomes fully concentrated, discards names and forms and realize Brahman
alone.

This is the state where a being becomes free of karma.


** 14. dhyānṃ - The Self-Contemplation
YogaSūtra maintains that an unbroken flow of thought in some particular object is Dhyānṃ. However, Śankara says that
remaining independent of everything as a result of unassailable thought, "I am verily Brahman" is Dhyānṃ

#+begin_quote
यदा विनियतं चित्तमात्मन्येवावतिष्ठते।

निःस्पृहः सर्वकामेभ्यो युक्त इत्युच्यते तदा।।6.18।।

When the subdued mind rests on the self alone, then, free of all yearning for objects of desire,
one is said to be fit for Yoga.

ŚrimadBhagvadGītā
#+end_quote


** 15. samādhiḥ - The complete Absorption
samādhiḥ is not an activity but an event. This is the end (as in culmination) of knowledge i.e. Vedānta. Here, a being gets
completely absorbed in homogeneous Consciousness, a state which is described as sat-chit-ānanda i.e. Truth-Consciousness-Bliss.


** References
- [[https://shop.advaitaashrama.org/product/aparokshanubhuti/?v=c86ee0d9d7ed][Aparokshanubhuti: of Sri Shankaracharya]] - Sri Shankaracharya | Swami Vimuktananda
- [[https://shop.advaitaashrama.org/product/eight-upanishads-vol-1/?v=c86ee0d9d7ed][Eight Upanishads (Vol. 1): With the Commentary of Shankaracharya]] - Sri Shankaracharya | Swami Gambhirananda
- [[https://www.gitasupersite.iitk.ac.in/srimad?language=dv&field_chapter_value=1&field_nsutra_value=1][ŚrimadBhagvadGītā]]
- [[https://eshop.chinmayamission.com/product/sadachara-1][Sadachara]] - Sri Shankaracharya | Swamini Vimalananda
- [[https://www.randhirbooks.com/product/%e0%a4%aa%e0%a4%be%e0%a4%a4%e0%a4%82%e0%a4%9c%e0%a4%b2-%e0%a4%af%e0%a5%8b%e0%a4%97%e0%a4%b8%e0%a5%82%e0%a4%a4%e0%a5%8d%e0%a4%b0-%e0%a4%af%e0%a5%8b%e0%a4%97%e0%a4%a6%e0%a4%b0%e0%a5%8d%e0%a4%b6%e0%a4%a8/][पातंजल योगसूत्र योगदर्शन]] - नंदलाल-दशोरा
- [[https://www.ramakrishnavivekananda.info/vivekananda/volume_1/raja-yoga/raja-yoga_contents.htm][Raja-Yoga]] - Swamī Vivekānanda
