---
title: "Teachings of my Father"
date: 2019-09-21T17:27:27+05:30
draft: false
categories: ["Lessons"]
tags: ["Learnings"]
---

** Be Calm - A short story
My father in his early years was curious to see/wear his uncle’s expensive watch. But, he was refrained from doing so. So, he tried it when the uncle was out on his job. As my father held the watch with curiosity, he dropped it on floor. He became nervous of the cold fear of breaking it. Now, with trembling hands, he picked up the watch and it was all good, but being in trembling hands it got dropped again. He picked up it again and it was still okay but the increased amount of fear made the watch dropped again and it got broken finally!

#+begin_quote
Moral: Stay calm and analyze the situation first. Probably, your nervousness and fear would do more damage to the situation than it really is!
#+end_quote


** Thought Control
#+begin_quote
When you think ill for someone, just think, you have already committed half of the crime.
#+end_quote

** Helping and Forgiving others
Help those who want to help themselves. Some people have the tendency to stay in dark; you may try to bring them to light but don’t get stuck with them there. Forgive people twice, and don’t think anymore in punishing them if they harm you third time.

** Be Brave
I would rather prefer to hear that you got beaten up than you got scared. Don’t run away from your fears, face them! That’s the only way you can get rid of them.
