---
title: "In Reality and in Goodness"
date: 2021-01-08T11:27:31+05:30
draft: false
categories: ["Vedānta"]
tags: ["BhagvadGītā"]
---

We know, we live in a world of cause and effect. So, each of our actions causes some effects on the world and on us. Whatever actions we perform, they leave residues in our mind. If we receive happiness from some action, we want more of it or fear the absence of it. On the other hand, if it is grief, we want to run away from it. These residues build our tendencies, make our world of likes and dislikes, and propel us to act further putting us in a vicious cycle of cause and effect. What, then, is the right way to act? Vedānta answers.

Vedānta says, perform all your actions with the utterance and intellectual conviction of =ॐ तत् सत् (Aum, Tat, Sat)=, a three-fold indication of the absolute reality i.e. =ब्रह्मन (Brahman)=.

** ॐ (Aum/Om)

Why Aum? Aum is a mystic symbol representing the entire existence:

1. How do we address which is everything in this world? By using our entire mechanism of speech! A starts from throat, M ends at lips, and in between U spans the start and end.

2. It represents different states of consciousness i.e. awake, sleep and dream in which our entire life experience delves. It additionally represents the fourth state i.e. state of super-consciousness.

** तत् (Tat)

To get rid of the residues of karma, mind has to be free from attachment and aversion. This is only possible when we perform actions in their true spirit of belongingness. We are just a small yet effective element of the existence, and, as such, everything belongs to Brahman, ‘That’.

** सत् (sat)

Sat, Truth, is that which is self existent and unchangeable with conditions and time. So, can we call our relative Reality as Sat? No. It is constantly changing. Sat is the Absolute Reality which is everywhere and found within.

The word Sat, therefore, is used in two aspects:

#+begin_quote
सद्भावे साधुभावे च

In Reality and In Goodness

Bhagvadītā 17.26
#+end_quote

Sat is used to denote our good actions which take us towards the Absolute Reality.

Hence, it is advised to the expounders of Brahman and seekers of Truth, to perform their actions with the utterance, intellectual conviction and in accordance with:

#+begin_quote
ॐ तत् सत्

That (Alone) is Truth
#+end_quote

Please read BhagvadGītā Chapter 17 verses 23-28 for the indication and explanation of Om Tat Sat.
