---
title: "Women are Spiritually advanced"
date: 2018-12-27T17:53:59+05:30
draft: false
Categories: ["Perspective"]
tags: ["Spirituality"]
---

I find that Women are spiritually advanced naturally, which means they are positioned at an advanced stage of human evolution. This assertion is not just a sentimental thought but logically true for three primary reasons:

** Intuition
You would agree that women are relatively more intuitive. When we think logically, our "I" thought rises and arranges several other thoughts, do calculations and decide what to do. What we tend to forget that "I" is yet another thought or when becomes decisive, it is an individual will, but still, it is also powered by some other energy which is the very source of our existence. When we don't have to go through all the calculations driven by "I" and get to know what needs to be done or what lies ahead by our very source, it is called intuition. We may call it grace too. And, women are more receptive of that effulgent grace.

** Emotional Strength
It is generally considered as weakness; in ignorance I would say! Our body consists of three sub-bodies: gross body(physical), subtle body(vital air, mind and intellect) and causal body (the seed of desires, also known as ignorance). The body beneath drives the body above. Causal body makes us do all the circus. Different non-pleasant thoughts arise in every human being because of some experiences, and choke in our mind matter. How do we release them is strength! If it flows in some expression of tears, it flushes the mind matter but if it doesn't find a way, it will only cause agitations in mind and disturb the intellect. So, being to able to channel our emotions is not a weakness, it is a strength!

** Selflessness
Look around and carefully at the roles of women in our lives. There is almost no notion of self. And, pick any religious philosophy, it will speak of losing little self for the welfare of all. Because, that One Self is manifested everywhere. When we lose the notion of our little individual self and work beyond it, doors to our ultimate evolution opens up. This is exactly how women work, beyond self!

The list could be longer. The message is that She is the energy by which creation happens and sustains. By respecting and aligning with this energy, we walk on our evolution, and by disrespecting we call for our downgrading. When an individual is downgraded, a society is downgraded. Let us call for the welfare of all!

Happy Women's Day! Oh, is it not today? Really?
